#!/bin/bash

set -e
set -a
. .secrets.env
set +a

docker image build -t build_monitor .
docker container run -dp $HTTP_PORT:$HTTP_PORT -e SECRET_KEY_BASE -e HTTP_PORT -e HTTPS_PORT -e PHX_HOST -e POOL_SIZE -e LOG_LEVEL --name build_monitor build_monitor
