#!/bin/bash
#keep this in sync with the fake .secrets.env

set -a
. .secrets.env
set +a

flyctl secrets set HTTP_PORT=$HTTP_PORT
flyctl secrets set HTTPS_PORT=$HTTPS_PORT
flyctl secrets set SECRET_KEY_BASE=$SECRET_KEY_BASE

#not setting the PHX_HOST because that happens at the fly.toml level
#flyctl secrets set PHX_HOST=$PHX_HOST

flyctl secrets set POOL_SIZE=$POOL_SIZE
flyctl secrets set LOG_LEVEL=$LOG_LEVEL

#not setting these properly because they're presumably set by fly.io itself?
#flyctl secrets set KEY_FILE="fake"
#flyctl secrets set CERT_FILE="fake"

flyctl secrets set PHX_SERVER=$PHX_SERVER
